tunnel: regod-backend
credentials-file: /Users/animeshjha/.cloudflared/regod-backend.json

ingress:
  - hostname: saint-bennett-attachment-quizzes.trycloudflare.com
    service: http://localhost:8000
    originRequest:
      # Enable WebSocket support
      noTLSVerify: true
      # WebSocket specific settings
      httpHostHeader: localhost:8000
  # Catch-all rule
  - service: http_status:404

